#!/bin/sh

## From https://ftp.gnu.org/gnu/binutils/binutils-2.17.tar.bz2
## Removed: `gprof/`
## Also requierd obj-c package
## Additional params to build with gcc-13

#mkdir -p /opt/9fdev/_XLAM/binutils-2.17-build
#cd /opt/9fdev/_XLAM/binutils-2.17-build
#CFLAGS="-g -O2 -fcommon" ../binutils-2.17/configure --prefix=/opt/9fdev/_XLAM/binut217 --disable-werror

make clean
CFLAGS="-g -O2 -fcommon" ./configure --prefix=/opt/9fdev/binut217 --disable-werror
MAKEINFO=true make -j$(nproc) all-binutils all-gas all-ld
make install

